#!/bin/bash

SRC="/home/mininet/networkAuth"
DST="/home/mininet/ryu/ryu/app/"
RYU="/home/mininet/ryu"

cp $SRC/simple_hubswitch.py $DST
cp $SRC/simple_hubswitch_tasks.py $DST
cp $SRC/error_parser.py $DST
cp $SRC/simple_udp_auth.py $DST


#PYTHONPATH=$RYU $RYU/bin/ryu-manager $RYU/ryu/app/simple_hubswitch.py $1
#PYTHONPATH=$RYU $RYU/bin/ryu-manager $RYU/ryu/app/simple_hubswitch_tasks.py $1
PYTHONPATH=$RYU $RYU/bin/ryu-manager $RYU/ryu/app/simple_udp_auth.py $1
